### ISSUE TITLE
Write a software architecture document

### ISSUE THREAD

**Issue by Hofmaier** [Zuehlke/HouseOfCards#14]
Enable a smooth project hand-over to our successors by describing the architecture and design decisions.

The document should contain a description of:
- components of the system
- design desicions
- game protocol (squence of game events)

**Comment by leozulfiu** [comment]
The same architecture overview which we used at the demo presentation for wgi could be done in the wiki.

**Comment by leozulfiu** [comment]
* Description of gradle modules
* Overview om the wiki main page

**Comment by leozulfiu** [comment]
See [Documentation](https://zuehlke.github.io/HouseOfCards/)
