### ISSUE TITLE
Structure Wiki

### ISSUE THREAD

**Issue by dominicmh** [Zuehlke/HouseOfCards#21]
Define categories and articles required for documentation:  [HoC Wiki](https://github.com/Zuehlke/HouseOfCards/wiki)

**Comment by bruderol** [comment]
@leozulfiu @dominicmh Just a recommendation: I recommend not to use github wikis, but use markdown files directly in your source repo instead ... you can use the gitbook tooling to easily produce a nice web page out of it (if you need that). This has many advantages comapred to the wiki. Let me know if you want to know more. 

In the scenarioo project, as well as in my current customer project we are using this, and also most open source projects do the same and try to avoid wikis, e.g. see https://github.com/angular/angular (major reason: docu should evolve and be versioned together with the software, which is not best supported by wikis).

**Comment by leozulfiu** [comment]
@bruderol gitbook seems cool! I will look into that. Thanks.
